name: build-test
# Based on the default "CMake" workflow file

# on: [push]
on:
  push:
    branches: [master]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  CLANG_BUILD_DIR: build_clang
  GCC_BUILD_DIR: build_gcc

jobs:
  build-gcc:
#    runs-on: ubuntu-latest
    runs-on: 'ubuntu-22.04'      # Sep 2022 - ubuntu-latest is 20.04 LTS

    steps:
    - uses: actions/checkout@v2

    - name: Create CMake Build Directory for Clang
      run: cmake -E make_directory ${{runner.workspace}}/${{env.CLANG_BUILD_DIR}}

#    - name: Install updated libstdc++ and Clang
#      run: sudo apt-get install libstdc++-10-dev clang-10

    - name: Configure CMake for Clang
      shell: bash
      working-directory: ${{runner.workspace}}/${{env.CLANG_BUILD_DIR}}
      run: cmake $GITHUB_WORKSPACE/tests -DUSE_CEST_VECTOR_ETC=1 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=clang++

    - name: Build with Clang
      working-directory: ${{runner.workspace}}/${{env.CLANG_BUILD_DIR}}
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test Clang Build
      working-directory: ${{runner.workspace}}/${{env.CLANG_BUILD_DIR}}
      shell: bash
      run: ctest -C $BUILD_TYPE

  # As above for Clang, so below for GCC 12:
  build-clang:
    runs-on: 'ubuntu-22.04'      # Sep 2022 - ubuntu-latest is 20.04 LTS

    steps:
    - uses: actions/checkout@v2

    - name: Install Recent GCC
      run: sudo apt install g++-12

    - name: Create CMake Build Directory for GCC
      run: cmake -E make_directory ${{runner.workspace}}/${{env.GCC_BUILD_DIR}}

    - name: Configure CMake for GCC
      shell: bash
      working-directory: ${{runner.workspace}}/${{env.GCC_BUILD_DIR}}
      run: cmake $GITHUB_WORKSPACE/tests -DUSE_CEST_VECTOR_ETC=1 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=g++-12

    - name: Build with GCC
      working-directory: ${{runner.workspace}}/${{env.GCC_BUILD_DIR}}
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test GCC Build
      working-directory: ${{runner.workspace}}/${{env.GCC_BUILD_DIR}}
      shell: bash
      run: ctest -C $BUILD_TYPE

  build-script-clang:
    runs-on: 'ubuntu-22.04'      # Sep 2022 - ubuntu-latest is 20.04 LTS

    steps:
    - name: Debugging
      run: |
          ls ${{github.workspace}}
          echo
          ls $GITHUB_WORKSPACE
          echo
          echo ok so far

    - name: Run build script
      run: $GITHUB_WORKSPACE/.github/scripts/build.sh ${CLANG_BUILD_DIR} $GITHUB_WORKSPACE/tests 1 $BUILD_TYPE clang++
      shell: bash
